services:
  - type: web
    name: attendance-app-backend
    env: python
    plan: free
    buildCommand: ./render/build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SQL_SERVER
        value: 103.25.174.53
      - key: DATABASE
        value: pragatiweb
      - key: DB_USERNAME
        value: sa
      - key: DB_PASSWORD
        value: India@123456#
